### ISSUE TITLE
AssertionError raising for form-data with empty name since multipart 1.0.0

### ISSUE THREAD

**Issue by jun66j5** [defnull/multipart#56]
AssertionError is raised when `parse_form_data` parsing form-data with empty name since multipart 1.0.0, but not with multipart 0.2.5 and `cgi.FieldStorage`.

(Originally reported at https://trac.edgewall.org/ticket/13788 and unit test exists at https://github.com/edgewall/trac/blob/1.6-stable/trac/web/tests/api.py#L534).

```!python
import io, multipart

print(f'multipart version: {multipart.__version__}')

boundary = '_BOUNDARY_'
form_data = f"""\
--{boundary}\r
Content-Disposition: form-data; name="foo"\r
\r
named value\r
--{boundary}\r
Content-Disposition: form-data; name=""\r
\r
name is empty\r
--{boundary}\r
Content-Disposition: form-data\r
\r
unnamed value\r
--{boundary}--\r
"""
form_data = form_data.encode('utf-8')
wsgi_input = io.BytesIO(form_data)
environ = {
    'REQUEST_METHOD': 'POST',
    'wsgi.input': wsgi_input,
    'CONTENT_LENGTH': str(len(form_data)),
    'CONTENT_TYPE': f'multipart/form-data; boundary="{boundary}"',
}
forms, files = multipart.parse_form_data(environ, charset='utf-8', strict=True)

actual = list(forms.iterallitems())
expected = [
    ('foo', 'named value'),
    ('', 'name is empty'),
    (None, 'unnamed value'),
]
assert expected == actual, f'{expected!r} != {actual!r}'
```

```
multipart version: 1.0.0
Traceback (most recent call last):
  File "/tmp/multipart-unnamed-part.py", line 29, in <module>
    forms, files = multipart.parse_form_data(environ, charset='utf-8', strict=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/multipart.py", line 790, in parse_form_data
    for part in MultipartParser(stream, boundary, content_length, **kwargs):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/multipart.py", line 596, in __iter__
    for part in self._part_iter:
                ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/multipart.py", line 634, in _iterparse
    for event in parser.parse(read(bufsize)):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/multipart.py", line 347, in parse
    self._current._update_size(index - offset)
  File "/venv/lib/python3.12/site-packages/multipart.py", line 493, in _update_size
    assert self.name and not self.complete
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by defnull** [comment]
Good find! The RFC strictly requires a `name` attribute, but it is allowed to be empty so the assert statement is indeed wrong.

We could reject segments with no name option in the header, but since there is no performance or security benefit in doing so, I think we should not be too pedantic here and just default to an empty string. I'll prepare a fix.
